//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSpaceComarcal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public int id { get; set; }
        public string id_alumno { get; set; }
        public Nullable<int> id_instancia { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual instancia instancia { get; set; }
    }
}
