//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSpaceComarcal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public int id { get; set; }
        public int id_alumno { get; set; }
        public int id_instancia { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<System.DateTime> fecha_expedicion { get; set; }
        public Nullable<bool> apto { get; set; }
        public string cod_factura { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual instancia instancia { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
